openapi: 3.0.0
info:
  title: Student API - Local Spelling Assessment App
  version: 1.0.0
paths:
  /auth/login:
    post:
      summary: Login using Avatar selection
      responses:
        200:
          description: JWT token returned
  /projects:
    get:
      summary: List assigned projects for the student
      responses:
        200:
          description: List of projects
  /projects/{id}:
    get:
      summary: Get project details (stimulus, instructions)
      responses:
        200:
          description: Project details
  /submissions/{project_id}:
    get:
      summary: Get current draft or submission status
    post:
      summary: Update draft content
    put:
      summary: Finalize submission (Submit)
  /ws/status:
    get:
      summary: WebSocket for live status sync (optional for student)
